# Generated by Django 5.1.1 on 2024-10-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expand', models.IntegerField(verbose_name='Expand')),
                ('way', models.IntegerField(choices=[(1, '支出'), (2, '收入')], default=1, verbose_name='way')),
                ('type', models.IntegerField(choices=[(1, '饮食'), (2, '购物'), (3, '出行'), (4, '教育'), (5, '娱乐'), (6, '人情'), (7, '居住'), (8, '医疗'), (9, '投资'), (10, '其他')], default=1, verbose_name='Type')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd',
            field=models.CharField(max_length=120, verbose_name='Password'),
        ),
    ]
