# Generated by Django 5.1.1 on 2024-10-15 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_account01', '0002_account_alter_user_name_alter_user_pwd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='expand',
        ),
    ]
