# Generated by Django 5.1.1 on 2024-10-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account01', '0004_account_expand'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='username',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_account01.user', verbose_name='Username'),
        ),
    ]
