# Generated by Django 5.1.1 on 2024-11-02 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_account01', '0005_account_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateField(default=None, verbose_name='Date'),
        ),
    ]
